### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "1997-06-16",
  "email": "govl3dnjs@gmail.com",
  "name": "myName",
  "password": "pw",
  "phone": "01011112222"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=govl3dnjs@gmail.com&code=nNPz9cdJCl


### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "govl3dnjs@gmail.com",
  "password": "pw"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2OTAzNjA0MDYsImV4cCI6MTY5MDQ0NjgwNn0.3wNODNH-hTaNNykDGIB-PG0h4KY4F1pxiC0KPMze_3U


### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2OTAzNjA0MDYsImV4cCI6MTY5MDQ0NjgwNn0.3wNODNH-hTaNNykDGIB-PG0h4KY4F1pxiC0KPMze_3U

{
  "from": "admin",
  "message": "돈 충전",
  "money": 90000
}


#######################

### 회원가입 (셀러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1999-06-16",
  "email": "govl3dnjs@gmail.com",
  "name": "김춘식",
  "password": "pw",
  "phone": "01011112222"
}

### 로그인 (셀러)
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "govl3dnjs@gmail.com",
  "password": "pw"
}

### 회원 정보 조회 (셀러)
GET http://localhost:8081/seller/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6ImxhdjczSFhHR0ZpK2V3dEFsQzFWaFE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkwMzYwMDcwLCJleHAiOjE2OTA0NDY0NzB9.EWbKCUHmI5i_nBCd1DetNQ32PQHnKkWYz5_THFF34mk
