### add product
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6ImxhdjczSFhHR0ZpK2V3dEFsQzFWaFE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkwMzYwMDcwLCJleHAiOjE2OTA0NDY0NzB9.EWbKCUHmI5i_nBCd1DetNQ32PQHnKkWYz5_THFF34mk

{
  "description": "상품 설명",
  "itmes": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스 2"
}

### add product_item
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6ImxhdjczSFhHR0ZpK2V3dEFsQzFWaFE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjkwMzYwMDcwLCJleHAiOjE2OTA0NDY0NzB9.EWbKCUHmI5i_nBCd1DetNQ32PQHnKkWYz5_THFF34mk

{
  "count": 1,
  "name": "280",
  "price": 100000,
  "productId": 17
}

### update product
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODk0MjMxODgsImV4cCI6MTY4OTUwOTU4OH0.weaKojLj45SMd720p8Qil0gtWqevnXqNZatpgvTQXSw

{
  "description": "상품설명",
  "itmes": [
    {
      "id": 2,
      "count": 20,
      "name": "295",
      "price": 135000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스1 한정판"
}


### update product_item
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6ImxhdjczSFhHR0ZpK2V3dEFsQzFWaFE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjg4NTM5NTQ1LCJleHAiOjE2ODg2MjU5NDV9.eI5iAuNhCzDaqUrEgk0cBocBBs6rrrMmpB7ORk0Vttc

{
  "id": 1,
  "count": 1,
  "name": "235",
  "price": 110000
}

### delete product (하위의 product_item 도 같이 지워진다)
DELETE http://localhost:8082/seller/product?id=1
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6ImxhdjczSFhHR0ZpK2V3dEFsQzFWaFE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjg4NTM5NTQ1LCJleHAiOjE2ODg2MjU5NDV9.eI5iAuNhCzDaqUrEgk0cBocBBs6rrrMmpB7ORk0Vttc

### delete product_item
DELETE http://localhost:8082/seller/product/item?id=3
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6ImxhdjczSFhHR0ZpK2V3dEFsQzFWaFE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjg4NTM5NTQ1LCJleHAiOjE2ODg2MjU5NDV9.eI5iAuNhCzDaqUrEgk0cBocBBs6rrrMmpB7ORk0Vttc

### 상품 검색
GET http://localhost:8082/search/product?name=나이키


### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json

### 카트 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2OTAzNjA0MDYsImV4cCI6MTY5MDQ0NjgwNn0.3wNODNH-hTaNNykDGIB-PG0h4KY4F1pxiC0KPMze_3U

{
  "description": "상품 설명",
  "id": 17,
  "items": [
    {
      "id": 44,
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스 2",
  "sellerId": 4
}

### 카트 확인
GET http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2OTAzNjA0MDYsImV4cCI6MTY5MDQ0NjgwNn0.3wNODNH-hTaNNykDGIB-PG0h4KY4F1pxiC0KPMze_3U

### (카트)주문
POST http://localhost:8082/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJJV0xBUE82M3JGVFM1eEYrY2xxb0g4WWQ0WHFUc1NzODhOTmNRTVZ3TkdnPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2OTAzNjA0MDYsImV4cCI6MTY5MDQ0NjgwNn0.3wNODNH-hTaNNykDGIB-PG0h4KY4F1pxiC0KPMze_3U

{
  "customerId": 3,
  "products": [
    {
      "id": 17,
      "sellerId": 4,
      "name": "나이키 에어포스 2",
      "description": "상품 설명",
      "items": [
        {
          "id": 44,
          "name": "270",
          "count": 1,
          "price": 100000
        }
      ]
    }
  ],
  "messages": []
}

